### ISSUE TITLE
Problème de submission pré-soutenance sur Moodle

### ISSUE THREAD

**Issue by pamellahani** [2024-2025-ECOM-INFO5-G03/App#12]
Bonjour,

L'ensemble de l'équipe n'arrive pas a rendre les diapos de pré-soutenance sur Moodle. Veuillez trouver une capture d'écran du problème. 
![image](https://github.com/user-attachments/assets/622c2e49-638c-4d3b-8415-37bd2a3bca30)

Pour le moment, nous avons push les slides sur notre repo Git (dans Docs). Veuillez trouver le lien ici: 
[lien slides pré-soutenance](https://github.com/2024-2025-ECOM-INFO5-G03/Docs/blob/main/Pr%C3%A9-Soutenance-3.pdf)

**Comment by alefebvr** [comment]
Bonjour,
Merci pour l'alerte !
C'est réglé normalement.
